### ISSUE TITLE
helper syscalls not decompiling on version 9.1.2

### ISSUE THREAD

**Issue by markpash** [Nalen98/eBPF-for-Ghidra#5]
Hi,

I've tried to run your plugin on ghidra 9.1.2 and I only see helper names and no other helper syscall attributes. (ret type etc.)
I see these warnings in eclipse logs when linking and running with ghidra and analysing an eBPF program.
`WARN  Decompiling syscall:0033, pcode error at syscall:0033: Unable to resolve constructor at syscall:0033 (DecompileCallback)` 
`WARN  Decompiling syscall:0001, pcode error at syscall:0001: Unable to resolve constructor at syscall:0001 (DecompileCallback)`

**Comment by Nalen98** [comment]
Hi!
Thank you for drawing attention to this problem. I found what exactly is the source of it. I missed that one of ghidra apis has been deprecated, so i fixed that. Now it's clear:
![FixedHelpers](https://user-images.githubusercontent.com/52778977/85198575-52d8ef80-b2f2-11ea-89b1-546f4acce328.png)
Check it out and let me know if something goes wrong (pre-release of extension 0.3.0+ghidra-9.1.2)

**Comment by markpash** [comment]
I tried again with the current master which includes your latest commit, and still no change :(.
[https://i.imgur.com/mVqFzmH.png](https://i.imgur.com/mVqFzmH.png)

**Comment by Nalen98** [comment]
Ok so I run the same eBPF binary with the current master again with Ghidra 9.1.2 and got clear helpers:
![Problem](https://user-images.githubusercontent.com/52778977/85230651-4fc92680-b3fa-11ea-8f01-ced307cbf131.png)

I think the source of problem is the ghidra build. I'm using latest stable build (2020-Feb-12).
